export const projects = [
  {
    id: 1,
    image: "/portfolio.png",
    title: "Personal Portfolio",
    technologies: ["NextJs", "Typescript", "TailwindCSS", "EmailJS"],
    liveUrl: "/",
    type: "Solo",
  },
  // {
  //   id: 2,
  //   image: "/sblink.png",
  //   title: "StartupBlink",
  //   technologies: [
  //     "NextJs",
  //     "TailwindCSS",
  //     "Typescript",
  //     "MySQL",
  //     "Docker",
  //     "Redis",
  //     "Python",
  //   ],
  //   liveUrl: "https://www.startupblink.com/",
  //   type: "Team",
  // },
  {
    id: 3,
    image: "/foodreceipe.png",
    title: "FoodRecipe",
    technologies: ["HTML", "CSS", "Javascript"],
    liveUrl: "https://https://github.com/lemasam/Food-Recipe/",
    type: "Solo",
  },
  // {
  //   id: 4,
  //   image: "/technerds.png",
  //   title: "TechNerds",
  //   technologies: ["React", "TailwindCSS", "Kontests API", "Firebase"],
  //   liveUrl: "https://technerds-web-app.netlify.app/",
  //   type: "Solo",
  // },
];
